-- ExamSphere Core Schema for Oracle Autonomous Database
-- All tables use VARCHAR2(36) for UUIDs to ensure Prisma compatibility.

-- 1. Tenancy & Identity
CREATE TABLE tenants (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    subdomain VARCHAR2(100) NOT NULL,
    type VARCHAR2(50) NOT NULL, -- INDIVIDUAL, INSTITUTE, SCHOOL, ENTERPRISE
    status VARCHAR2(50) DEFAULT 'ACTIVE' NOT NULL, -- ACTIVE, SUSPENDED, TERMINATED
    branding CLOB CHECK (branding IS JSON),
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE users (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    tenant_id VARCHAR2(36) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    password_hash VARCHAR2(255),
    status VARCHAR2(50) DEFAULT 'ACTIVE' NOT NULL,
    last_login_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE roles (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    tenant_id VARCHAR2(36) NOT NULL,
    name VARCHAR2(100) NOT NULL,
    scope VARCHAR2(50) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE permissions (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    resource VARCHAR2(100) NOT NULL,
    action VARCHAR2(100) NOT NULL,
    constraints CLOB CHECK (constraints IS JSON)
);

CREATE TABLE user_roles (
    user_id VARCHAR2(36) NOT NULL,
    role_id VARCHAR2(36) NOT NULL,
    assigned_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE role_permissions (
    role_id VARCHAR2(36) NOT NULL,
    permission_id VARCHAR2(36) NOT NULL,
    PRIMARY KEY (role_id, permission_id)
);

-- 2. Syllabus Hierarchy
CREATE TABLE exams (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    code VARCHAR2(50) NOT NULL, -- JEE_MAIN, JEE_ADVANCED, NEET
    name VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE subjects (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    exam_id VARCHAR2(36) NOT NULL,
    name VARCHAR2(100) NOT NULL,
    tenant_id VARCHAR2(36), -- NULL for global
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE units (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    subject_id VARCHAR2(36) NOT NULL,
    name VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE chapters (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    unit_id VARCHAR2(36) NOT NULL,
    name VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE topics (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    chapter_id VARCHAR2(36) NOT NULL,
    name VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE concepts (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    topic_id VARCHAR2(36) NOT NULL,
    name VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at TIMESTAMP(6) WITH TIME ZONE
);

-- 3. Question Bank
CREATE TABLE questions (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    tenant_id VARCHAR2(36) NOT NULL,
    type VARCHAR2(50) NOT NULL,
    status VARCHAR2(50) DEFAULT 'DRAFT' NOT NULL,
    difficulty VARCHAR2(50) NOT NULL,
    source_type VARCHAR2(50) NOT NULL,
    exam_id VARCHAR2(36) NOT NULL,
    subject_id VARCHAR2(36) NOT NULL,
    created_by VARCHAR2(36) NOT NULL,
    current_version NUMBER(10) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE question_versions (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    question_id VARCHAR2(36) NOT NULL,
    version_no NUMBER(10) NOT NULL,
    statement CLOB NOT NULL,
    option_a CLOB,
    option_b CLOB,
    option_c CLOB,
    option_d CLOB,
    correct_options VARCHAR2(100) NOT NULL, -- e.g., "A", "A,C", "B"
    solution CLOB,
    hint_level_1 CLOB,
    hint_level_2 CLOB,
    hint_level_3 CLOB,
    marks_correct NUMBER(5,2) NOT NULL,
    marks_wrong NUMBER(5,2) DEFAULT 0 NOT NULL,
    pyq_year NUMBER(4),
    pyq_exam_session VARCHAR2(50),
    pyq_shift VARCHAR2(50),
    est_time_sec NUMBER(6),
    language VARCHAR2(10) DEFAULT 'en' NOT NULL,
    change_summary VARCHAR2(500),
    created_by VARCHAR2(36) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE question_topics (
    question_id VARCHAR2(36) NOT NULL,
    topic_id VARCHAR2(36) NOT NULL,
    PRIMARY KEY (question_id, topic_id)
);

CREATE TABLE tags (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    name VARCHAR2(100) NOT NULL
);

CREATE TABLE question_tags (
    question_id VARCHAR2(36) NOT NULL,
    tag_id VARCHAR2(36) NOT NULL,
    PRIMARY KEY (question_id, tag_id)
);

CREATE TABLE question_images (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    question_id VARCHAR2(36) NOT NULL,
    url VARCHAR2(1024) NOT NULL,
    purpose VARCHAR2(50) NOT NULL, -- STATEMENT, OPTION, SOLUTION
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE question_review_logs (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    question_id VARCHAR2(36) NOT NULL,
    reviewer_id VARCHAR2(36) NOT NULL,
    action VARCHAR2(50) NOT NULL,
    comment CLOB,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

-- 4. Exam Engine
CREATE TABLE test_templates (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    tenant_id VARCHAR2(36) NOT NULL,
    name VARCHAR2(255) NOT NULL,
    type VARCHAR2(50) NOT NULL,
    exam_id VARCHAR2(36) NOT NULL,
    configuration CLOB CHECK (configuration IS JSON),
    duration_min NUMBER(6) NOT NULL,
    total_marks NUMBER(8,2) NOT NULL,
    scheduled_start TIMESTAMP(6) WITH TIME ZONE,
    scheduled_end TIMESTAMP(6) WITH TIME ZONE,
    status VARCHAR2(50) DEFAULT 'DRAFT' NOT NULL,
    created_by VARCHAR2(36) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE test_sections (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    template_id VARCHAR2(36) NOT NULL,
    subject_id VARCHAR2(36) NOT NULL,
    name VARCHAR2(100) NOT NULL,
    question_count NUMBER(6) NOT NULL,
    marks_correct NUMBER(5,2) NOT NULL,
    marks_wrong NUMBER(5,2) DEFAULT 0 NOT NULL,
    duration_min NUMBER(6),
    order_no NUMBER(4) NOT NULL
);

CREATE TABLE test_section_questions (
    section_id VARCHAR2(36) NOT NULL,
    question_id VARCHAR2(36) NOT NULL,
    order_no NUMBER(6) NOT NULL,
    PRIMARY KEY (section_id, question_id)
);

CREATE TABLE test_sessions (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    template_id VARCHAR2(36) NOT NULL,
    user_id VARCHAR2(36) NOT NULL,
    tenant_id VARCHAR2(36) NOT NULL,
    status VARCHAR2(50) DEFAULT 'NOT_STARTED' NOT NULL,
    started_at TIMESTAMP(6) WITH TIME ZONE,
    submitted_at TIMESTAMP(6) WITH TIME ZONE,
    time_spent_sec NUMBER(10),
    total_score NUMBER(8,2),
    rank_estimate NUMBER(10),
    percentile_estimate NUMBER(5,2),
    device_info CLOB CHECK (device_info IS JSON),
    ip_address VARCHAR2(45),
    user_agent VARCHAR2(500),
    fullscreen_violations NUMBER(4) DEFAULT 0 NOT NULL,
    tab_switches NUMBER(4) DEFAULT 0 NOT NULL,
    window_blurs NUMBER(4) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE test_responses (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
    session_id VARCHAR2(36) NOT NULL,
    question_id VARCHAR2(36) NOT NULL,
    section_id VARCHAR2(36) NOT NULL,
    response_value CLOB,
    status VARCHAR2(50) DEFAULT 'NOT_VISITED' NOT NULL,
    time_spent_sec NUMBER(8) DEFAULT 0 NOT NULL,
    is_correct NUMBER(1) DEFAULT 0 NOT NULL,
    marks_awarded NUMBER(5,2) DEFAULT 0 NOT NULL,
    visited_at TIMESTAMP(6) WITH TIME ZONE,
    answered_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
) PARTITION BY RANGE (created_at) (
    PARTITION test_resp_2024_q1 VALUES LESS THAN (TO_DATE('2024-04-01', 'YYYY-MM-DD')),
    PARTITION test_resp_2024_q2 VALUES LESS THAN (TO_DATE('2024-07-01', 'YYYY-MM-DD')),
    PARTITION test_resp_2024_q3 VALUES LESS THAN (TO_DATE('2024-10-01', 'YYYY-MM-DD')),
    PARTITION test_resp_2024_q4 VALUES LESS THAN (TO_DATE('2025-01-01', 'YYYY-MM-DD')),
    PARTITION test_resp_2025_q1 VALUES LESS THAN (TO_DATE('2025-04-01', 'YYYY-MM-DD')),
    PARTITION test_resp_max VALUES LESS THAN (MAXVALUE)
);

-- 5. Practice & Analytics
CREATE TABLE practice_sessions (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    user_id VARCHAR2(36) NOT NULL,
    tenant_id VARCHAR2(36) NOT NULL,
    type VARCHAR2(50) NOT NULL,
    target_topic_id VARCHAR2(36),
    started_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    ended_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE practice_responses (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
    session_id VARCHAR2(36) NOT NULL,
    question_id VARCHAR2(36) NOT NULL,
    response_value CLOB,
    is_correct NUMBER(1) DEFAULT 0 NOT NULL,
    time_spent_sec NUMBER(8) NOT NULL,
    hint_used NUMBER(1) DEFAULT 0 NOT NULL,
    explanation_viewed NUMBER(1) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
) PARTITION BY RANGE (created_at) (
    PARTITION prac_resp_2024_q1 VALUES LESS THAN (TO_DATE('2024-04-01', 'YYYY-MM-DD')),
    PARTITION prac_resp_2024_q2 VALUES LESS THAN (TO_DATE('2024-07-01', 'YYYY-MM-DD')),
    PARTITION prac_resp_2024_q3 VALUES LESS THAN (TO_DATE('2024-10-01', 'YYYY-MM-DD')),
    PARTITION prac_resp_2024_q4 VALUES LESS THAN (TO_DATE('2025-01-01', 'YYYY-MM-DD')),
    PARTITION prac_resp_2025_q1 VALUES LESS THAN (TO_DATE('2025-04-01', 'YYYY-MM-DD')),
    PARTITION prac_resp_max VALUES LESS THAN (MAXVALUE)
);

CREATE TABLE analytics_snapshots (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
    user_id VARCHAR2(36) NOT NULL,
    tenant_id VARCHAR2(36) NOT NULL,
    period_type VARCHAR2(20) NOT NULL,
    period_start TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    period_end TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    metrics CLOB CHECK (metrics IS JSON),
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
) PARTITION BY LIST (tenant_id) (
    PARTITION an_default VALUES (DEFAULT)
);

CREATE TABLE weak_topics (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    user_id VARCHAR2(36) NOT NULL,
    tenant_id VARCHAR2(36) NOT NULL,
    topic_id VARCHAR2(36) NOT NULL,
    weakness_score NUMBER(5,2) NOT NULL,
    last_assessed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE rank_predictions (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    user_id VARCHAR2(36) NOT NULL,
    exam_id VARCHAR2(36) NOT NULL,
    predicted_rank NUMBER(10) NOT NULL,
    predicted_percentile NUMBER(5,2) NOT NULL,
    computed_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    model_version VARCHAR2(20) NOT NULL
);

-- 6. AI, Doubt, Subscription, Notification
CREATE TABLE ai_conversations (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    user_id VARCHAR2(36) NOT NULL,
    tenant_id VARCHAR2(36) NOT NULL,
    type VARCHAR2(50) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE ai_messages (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    conversation_id VARCHAR2(36) NOT NULL,
    role VARCHAR2(20) NOT NULL,
    content CLOB NOT NULL,
    provider VARCHAR2(50) NOT NULL,
    tokens_in NUMBER(10),
    tokens_out NUMBER(10),
    cost_inr NUMBER(10,4),
    latency_ms NUMBER(10),
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE doubts (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    user_id VARCHAR2(36) NOT NULL,
    tenant_id VARCHAR2(36) NOT NULL,
    question_id VARCHAR2(36),
    title VARCHAR2(255) NOT NULL,
    body CLOB NOT NULL,
    status VARCHAR2(50) DEFAULT 'OPEN' NOT NULL,
    priority VARCHAR2(20) DEFAULT 'MEDIUM' NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE doubt_responses (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    doubt_id VARCHAR2(36) NOT NULL,
    author_id VARCHAR2(36) NOT NULL,
    body CLOB NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE plans (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    code VARCHAR2(50) NOT NULL,
    name VARCHAR2(100) NOT NULL,
    price_inr NUMBER(10,2) NOT NULL,
    billing_cycle VARCHAR2(20) NOT NULL,
    features CLOB CHECK (features IS JSON),
    is_active NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE TABLE subscriptions (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    user_id VARCHAR2(36) NOT NULL,
    tenant_id VARCHAR2(36) NOT NULL,
    plan_id VARCHAR2(36) NOT NULL,
    status VARCHAR2(50) NOT NULL,
    started_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    ends_at TIMESTAMP(6) WITH TIME ZONE,
    cancelled_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE notifications (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
    user_id VARCHAR2(36) NOT NULL,
    tenant_id VARCHAR2(36) NOT NULL,
    type VARCHAR2(50) NOT NULL,
    title VARCHAR2(255) NOT NULL,
    body CLOB,
    payload CLOB CHECK (payload IS JSON),
    channel VARCHAR2(20) DEFAULT 'IN_APP' NOT NULL,
    status VARCHAR2(20) DEFAULT 'UNREAD' NOT NULL,
    read_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
) PARTITION BY LIST (tenant_id) (
    PARTITION notif_default VALUES (DEFAULT)
);

-- 7. Audit & Events
CREATE TABLE audit_logs (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
    tenant_id VARCHAR2(36),
    actor_id VARCHAR2(36),
    action VARCHAR2(100) NOT NULL,
    resource_type VARCHAR2(100) NOT NULL,
    resource_id VARCHAR2(36),
    before_state CLOB,
    after_state CLOB,
    ip_address VARCHAR2(45),
    user_agent VARCHAR2(500),
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
) PARTITION BY RANGE (created_at) (
    PARTITION audit_2024_q1 VALUES LESS THAN (TO_DATE('2024-04-01', 'YYYY-MM-DD')),
    PARTITION audit_2024_q2 VALUES LESS THAN (TO_DATE('2024-07-01', 'YYYY-MM-DD')),
    PARTITION audit_2024_q3 VALUES LESS THAN (TO_DATE('2024-10-01', 'YYYY-MM-DD')),
    PARTITION audit_2024_q4 VALUES LESS THAN (TO_DATE('2025-01-01', 'YYYY-MM-DD')),
    PARTITION audit_2025_q1 VALUES LESS THAN (TO_DATE('2025-04-01', 'YYYY-MM-DD')),
    PARTITION audit_max VALUES LESS THAN (MAXVALUE)
);

CREATE TABLE domain_events (
    id VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
    tenant_id VARCHAR2(36),
    type VARCHAR2(100) NOT NULL,
    payload CLOB CHECK (payload IS JSON),
    occurred_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    processed_at TIMESTAMP(6) WITH TIME ZONE
) PARTITION BY RANGE (occurred_at) (
    PARTITION event_2024_q1 VALUES LESS THAN (TO_DATE('2024-04-01', 'YYYY-MM-DD')),
    PARTITION event_2024_q2 VALUES LESS THAN (TO_DATE('2024-07-01', 'YYYY-MM-DD')),
    PARTITION event_2024_q3 VALUES LESS THAN (TO_DATE('2024-10-01', 'YYYY-MM-DD')),
    PARTITION event_2024_q4 VALUES LESS THAN (TO_DATE('2025-01-01', 'YYYY-MM-DD')),
    PARTITION event_2025_q1 VALUES LESS THAN (TO_DATE('2025-04-01', 'YYYY-MM-DD')),
    PARTITION event_max VALUES LESS THAN (MAXVALUE)
);